# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20161228_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionproducto',
            name='unidad',
            field=models.CharField(blank=True, choices=[(b'cm', b'centimetro'), (b'und', b'unidad'), (b'm', b'metro'), (b'lt', b'litro')], max_length=10, null=True),
        ),
    ]
