# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_seccionproducto_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialproducto',
            name='vista',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seccionproducto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
