# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20161229_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialproducto',
            name='seccion',
        ),
    ]
