# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_materialproducto_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vendidos',
        ),
    ]
