# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20171001_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendidos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
