# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170822_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
