# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 16:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsweb', '0002_auto_20161210_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='cuerpo',
        ),
        migrations.AddField(
            model_name='bloque',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
