# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20161228_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Proveedor'),
        ),
    ]
