# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='full_name_invitado',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
