# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-24 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('pedido', '0004_auto_20161229_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMetodoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('restriccion_precio', models.DecimalField(decimal_places=2, default=0, help_text=b'Todo precio mayor que ese numero lo habilita', max_digits=12)),
                ('exepciones', models.ManyToManyField(blank=True, help_text=b'Menos en este esta habilitado', related_name='restricciones_menos', to='ubigeo.Ubigeo')),
                ('restricciones', models.ManyToManyField(blank=True, help_text=b'Solo en este lugar esta habilitado', related_name='restricciones_solo', to='ubigeo.Ubigeo')),
            ],
        ),
        migrations.RemoveField(
            model_name='metodoenvio',
            name='exepciones',
        ),
        migrations.RemoveField(
            model_name='metodoenvio',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='metodoenvio',
            name='restriccion_precio',
        ),
        migrations.RemoveField(
            model_name='metodoenvio',
            name='restricciones',
        ),
        migrations.AddField(
            model_name='metodoenvio',
            name='grupo_metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.GrupoMetodoEnvio'),
        ),
    ]
