# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_auto_20170824_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='iconos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
