# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_auto_20170922_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[(b'autenticado', '<b>Autenticado</b> - Usted se encuentra idenficado en la plataforma'), (b'metodo_envio', '<b>Metodo de Envio</b> - Ya selecciono el metodo de envio, esperando metodo de pago'), (b'metodo_pago', '<b>Metodo de Pago</b> - Ya selecciono el metodo de pago'), (b'esperando_pago', '<b>Esperando Pago</b> - Ya selecciono el metodo de pago, pero aun no se realiza el pago'), (b'pagado', '<b>Pagado</b> - El pago se realizo correctamente, espere el envio del producto'), (b'error_pago', '<b>Error en Pago</b> - Ocurrio un error al pagar'), (b'enviado', '<b>Enviado</b> - El producto fue enviado'), (b'devuelto', '<b>Devuelto</b> - El producto fue devuelto'), (b'fucionado', '<b>Fusionado</b> - Este Pedido se Fusiono con otro pedido')], default=b'autenticado', max_length=120),
        ),
    ]
