# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-22 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_auto_20170922_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='valido',
            field=models.BooleanField(default=False),
        ),
    ]
